### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by davegraham92120** [Luidog/gulp-fm-icon-converter#1]
Instead of writing the converted file, I'm getting a standard-icons folder in the output directory. 

Can you tell me what I'm doing wrong? 
http://youtu.be/sB995g7ptLY

Dave

**Comment by Luidog** [comment]
@davegraham92120  Thanks for the heads up. It looks like some of the cheerio might have changed the way they handle files. I will take a look. of course I would also accept a PR :)

**Comment by Luidog** [comment]
Closed with commit 032a8e004e29c08f681d2751e752e6e5a20dc8ab 

@davegraham92120  if you are still having issues please open a new issue
