### ISSUE TITLE
error when running gulp

### ISSUE THREAD

**Issue by metalox** [Luidog/gulp-fm-icon-converter#3]
@Luidog 
node -v: v10.6.0
gulp - v: CLI version 2.0.1, Local version 3.9.1
Mac OS 10.13 .5
I get the following error and the svg file in standard-icons is not converted.
Error:
``gulp[90580]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100033d65 node::Abort() [/Users/benm/.nvm/versions/node/v10.6.0/bin/node]
 2: 0x100032dab node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/Users/benm/.nvm/versions/node/v10.6.0/bin/node]
 3: 0x10005a505 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/benm/.nvm/versions/node/v10.6.0/bin/node]
 4: 0x10022b83f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/benm/.nvm/versions/node/v10.6.0/bin/node]
 5: 0x10022a9d8 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/benm/.nvm/versions/node/v10.6.0/bin/node]
 6: 0x10022a3a7 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/benm/.nvm/versions/node/v10.6.0/bin/node]
 7: 0x12bead6041bd
Abort trap: 6``

**Comment by Luidog** [comment]
@metalox Thanks for posting this issue. Sorry its taken me a bit to take a look at issue. I have been very busy with [fms-api-client](https://github.com/luidog/fms-api-client). I am currently looking here for a solve to your problem: https://github.com/gulpjs/gulp/issues/2162

**Comment by Luidog** [comment]
This issue should be closed with commit db70fb45120c304e7afe045292bb8ac9fed07450. @metalox please remove and reinstall your node modules. If you still have this issue after reinstalling please open a new issue.
